services:
    app:
        build:
            context: ./
            target: app-prod
            dockerfile: docker/Dockerfile
        restart: unless-stopped
        environment:
            APP_ENV: ${APP_ENV}
            APP_SECRET: ${APP_SECRET}
            SERVER_NAME: ${SERVER_NAME}
            DATABASE_URL: ${DATABASE_URL}
            MEILISEARCH_DSN: ${MEILISEARCH_DSN}
            REGISTRY_DATABASE_CH_FILE: /www/var/data/data-ch.sqlite
            REGISTRY_DATABASE_LI_FILE: /www/var/data/data-li.csv
            REGISTRY_DATABASE_REFRESH_ENABLED: true
            MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN:-doctrine://default}
        ports:
            - "7800:80"
